name: "Run tests"
on:
  pull_request:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
      - name: install
        run: npm ci 
      - name: Lint
        run: npm run lint

  SodaSpec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
      - name: install
        run: npm ci 
      - name: Run SodaSpec
        run: npx jasmine spec/Soda.spec.js

  SodaMachineSpec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
      - name: install
        run: npm ci 
      - name: Run SodaMachineSpec
        run: npx jasmine spec/SodaMachine.spec.js
